# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4edc7e3be3b7ac80315da919736771e8e3a9e516b8fb85e4cd5cc7d4975a04865af23d12d398a726a7da545b606db24e7e1620fc6d57f71b354c51d49b1f85eb

test:
  secret_key_base: c1a4b81f1e8ea93ad350a35855b350d7a61ac3951d8a89d8776e2660fdad3f2ce12f9b803ef48be032af088c30d02ab81c99612daff1c73a62e08a5e6a12d552

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
